language: node_js
notifications:
  email: true
node_js:
  - '10.0'
  - '9.11'
deploy:
  provider: npm
  email: 'i@lenconda.top'
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
before_script:
  - unset CI
script:
  - npm run test
